---
- hosts: servers
  become_user: ubuntu

  tasks:

  - name: Apply Kubernetes manifest with PATH
    ansible.builtin.command:
     cmd: kubectl apply -f ds.yml
    environment:
      PATH: /usr/local/bin:/usr/bin:/bin
